# Generated by Django 5.2.17 on 2026-09-29 13:10

from django.db import migrations


def rename_show_gamification_to_show_leaderboard(apps, schema_editor):
    """Rename any existing SHOW_GAMIFICATION Setting row to SHOW_LEADERBOARD,
    preserving its current_value and audit metadata (AAP-94021)."""
    Setting = apps.get_model("dynamic_settings", "Setting")
    Setting.objects.filter(setting_key="SHOW_GAMIFICATION").update(setting_key="SHOW_LEADERBOARD")


def rename_show_leaderboard_to_show_gamification(apps, schema_editor):
    """Reverse: rename SHOW_LEADERBOARD back to SHOW_GAMIFICATION."""
    Setting = apps.get_model("dynamic_settings", "Setting")
    Setting.objects.filter(setting_key="SHOW_LEADERBOARD").update(setting_key="SHOW_GAMIFICATION")


class Migration(migrations.Migration):
    dependencies = [
        ("dynamic_settings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            rename_show_gamification_to_show_leaderboard,
            rename_show_leaderboard_to_show_gamification,
        ),
    ]
